name: australiacash-core # you probably want to 'snapcraft register <name>'
version: '1.14.5'
summary: Reference client of AustraliaCash, a peer-to-peer digital currency like Bitcoin.
description: |
  AustraliaCash is a cryptocurrency like Bitcoin, although it does not use SHA256 as its proof of work (POW). Taking development cues from Tenebrix and Litecoin, AustraliaCash currently employs a simplified variant of scrypt. MIT licenced.

base: core18
grade: stable
confinement: strict
architectures:
  - build-on: [amd64, i386, arm64]

apps:
  d:
    command: australiacashd
    plugs: [home, removable-media, network, network-bind]
    environment:
    # Override HOME so the datadir is located at ~/snap/australiacash-core/common/.australiacash/ instead of ~/snap/australiacash-core/current/.australiacash/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: qt4-launch australiacash-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: australiacash-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  australiacash-core:
    plugin: nil
    override-build: |
      echo "Downloading files..."
      wget https://github.com/australiacash/australiacash/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/australiacash-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      wget https://github.com/australiacash/gitian.sigs/archive/refs/heads/master.zip
      unzip master.zip
      echo "Verifying secure hash matches signed values..."
      checksum=$(sha256sum australiacash-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz)
      if ! (grep -r $checksum * | grep australiacash-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz); then
        echo "Secure hash not verified."
        return
      else
        echo "Secure hash verified."
      fi
      tar -xvf australiacash-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      echo "Running tests..."
      if ! (australiacash-${SNAPCRAFT_PROJECT_VERSION}/bin/test_australiacash); then
        echo "AustraliaCash tests failed."
        return
      else
        echo "AustraliaCash tests passed."
      fi
      echo "Installing AustraliaCash..."
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin australiacash-${SNAPCRAFT_PROJECT_VERSION}/bin/australiacashd
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin australiacash-${SNAPCRAFT_PROJECT_VERSION}/bin/australiacash-qt
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin australiacash-${SNAPCRAFT_PROJECT_VERSION}/bin/australiacash-cli
      wget https://raw.githubusercontent.com/australiacash/australiacash/master/share/pixmaps/australiacash128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps australiacash128.png
    build-packages:
      - unzip
      - wget
    stage-packages:
      - libfreetype6
      - libpng16-16
      - libx11-xcb1
      - libx11-6
      - libfontconfig
  qt4conf:
    build-packages:
      - dpkg-dev
    plugin: make
    source: https://github.com/kyrofa/qt4conf.git
